# -*- coding: utf-8 -*-
"""Random_password_generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vpCBMlIX6QffxWFAJp9oYVPN77GX3aiV
"""

# Importing random module
import random

# Defining the character sets
letters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
numbers = "0123456789"
symbols = "!@#$%^&*()_+-=[]{};:,./<>?"

# Ask the user for the password length and character preferences
length = int(input("Enter the password length: "))
use_letters = input("Do you want to use letters? (y/n) ")
use_numbers = input("Do you want to use numbers? (y/n) ")
use_symbols = input("Do you want to use symbols? (y/n) ")

# Create an empty password string
password = ""

# Create a list of possible characters based on the user's preferences
possible_chars = ""
if use_letters == "y":
  possible_chars += letters
if use_numbers == "y":
  possible_chars += numbers
if use_symbols == "y":
  possible_chars += symbols

# Check if the list of possible characters is not empty
if possible_chars != "":
  # Loop for the password length times
  for i in range(length):
    # Choose a random character from the possible characters and append it to the password
    password += random.choice(possible_chars)
  # Print the password
  print("Your password is:", password)
else:
  # Print an error message
  print("You need to choose at least one character type.")